version: "3.6"

services:
  api-prod:
    container_name: fr-api-prod
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "${PROD_API_PORT}:8000"

  client-prod:
    container_name: fr-client-prod
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "${PROD_CLIENT_PORT}:80"

