version: "3.6"

services:
  api-dev:
    container_name: fr-api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${DEV_API_PORT}:5000"
    volumes:
      - ./api:/app

  client-dev:
    container_name: fr-client
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - "${DEV_CLIENT_PORT}:3000"
    depends_on:
      - "api-dev"
    environment:
      - CHOKIDAR_USEPOLLING=true

